"use client";
import {useEffect,useState} from "react";
import type {PersonalEvent} from "./data/personal-events";

export function PersonalEventDialog({open,year,month,day,editing,onClose,onSave}:{open:boolean;year:number;month:number;day:number;editing?:PersonalEvent|null;onClose:()=>void;onSave:(event:PersonalEvent)=>void}){
 const [title,setTitle]=useState(""),[kind,setKind]=useState<"纪念"|"日程">("纪念"),[yearly,setYearly]=useState(true),[eventDate,setEventDate]=useState("2026-01-01"),[datePickerOpen,setDatePickerOpen]=useState(false),[picker,setPicker]=useState({year:2026,month:1});
 useEffect(()=>{if(open){const chosenYear=editing?.year??year,chosenMonth=editing?.month||month;setTitle(editing?.title||"");setKind(editing?.kind||"纪念");setYearly(editing?.yearly??true);setEventDate(`${chosenYear}-${String(chosenMonth).padStart(2,"0")}-${String(editing?.day||day).padStart(2,"0")}`);setPicker({year:chosenYear,month:chosenMonth});setDatePickerOpen(false)}},[open,year,month,day,editing]);
 if(!open)return null;
 const [selectedYear,selectedMonth,selectedDay]=eventDate.split("-").map(Number),first=(new Date(picker.year,picker.month-1,1).getDay()+6)%7,days=new Date(picker.year,picker.month,0).getDate();
 const moveMonth=(amount:number)=>{const d=new Date(picker.year,picker.month-1+amount,1);setPicker({year:d.getFullYear(),month:d.getMonth()+1})};
 const chooseDate=(chosenDay:number)=>{setEventDate(`${picker.year}-${String(picker.month).padStart(2,"0")}-${String(chosenDay).padStart(2,"0")}`);setDatePickerOpen(false)};
 const submit=()=>{const clean=title.trim();if(!clean)return;onSave({id:editing?.id||`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,title:clean,year:selectedYear,month:selectedMonth,day:selectedDay,kind,yearly});onClose()};
 return <div className="personal-dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="personal-dialog" role="dialog" aria-modal="true" aria-labelledby="personal-dialog-title"><header><span>个人日历</span><button onClick={onClose} aria-label="关闭">×</button></header><h2 id="personal-dialog-title">{editing?"修改一件事":"记下一件事"}</h2><p className="personal-dialog-intro">留一笔清楚的记号，到时从容照看。</p><div className="personal-event-date"><span>日期</span><button onClick={()=>{setPicker({year:selectedYear,month:selectedMonth});setDatePickerOpen(x=>!x)}} aria-expanded={datePickerOpen}>{selectedYear}年{selectedMonth}月{selectedDay}日 <i>{datePickerOpen?"收起":"选择"}</i></button></div>{datePickerOpen&&<div className="personal-date-picker"><header><button onClick={()=>moveMonth(-1)} aria-label="上个月">‹</button><strong>{picker.year}年{picker.month}月</strong><button onClick={()=>moveMonth(1)} aria-label="下个月">›</button></header><div className="personal-picker-week">{["一","二","三","四","五","六","日"].map(x=><span key={x}>{x}</span>)}</div><div className="personal-picker-days">{Array.from({length:first},(_,i)=><i key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>i+1).map(n=><button className={picker.year===selectedYear&&picker.month===selectedMonth&&n===selectedDay?"selected":""} key={n} onClick={()=>chooseDate(n)}>{n}</button>)}</div></div>}<label className="personal-title-field"><span>记事内容</span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="例如：师父生日、共修、复诊"/></label><div className="personal-options"><span>归为</span><div className="personal-kind"><button className={kind==="纪念"?"active":""} onClick={()=>setKind("纪念")}>纪念</button><button className={kind==="日程"?"active":""} onClick={()=>setKind("日程")}>日程</button></div></div><div className="personal-reminders"><label className="personal-toggle"><span><strong>每年重复</strong><small>纪念日会自动显示倒计时</small></span><input type="checkbox" checked={yearly} onChange={e=>setYearly(e.target.checked)}/><i/></label></div><button className="personal-save" disabled={!title.trim()} onClick={submit}>{editing?"保存修改":"存入此日"}</button><p className="personal-local-note">只留在这台设备中</p></section></div>;
}
